server/views/main_views.py
from flask import (
    Blueprint,
    jsonify,
    make_response,
    render_template,
    request,
)
from datetime import datetime
from server.models import Block, Transaction
from server.transfer import Transfer
from server.utils import get_blockchain
from server import utils
from server.mining import Mine
from server.forms import MinigForm
from server.wallet import Wallet
from server import db
from server.blockchain import BlockChain

# Blueprint 객체 bp를 생성합니다.
bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/', methods=['GET'])
def home():
    '''메인 화면'''
    form = MinigForm()
    return render_template(
        'mining.html',
        form=form,
    )


@bp.route('/get_chain/', methods=['GET'])
def get_chain():
    '''블록체인 가져오기'''
    block_chain = utils.get_blockchain()
    response = {
        # 'chain': 'under testing',
        'chain': block_chain.get('chain'),
    }
    return jsonify(response), 200


@bp.route('/transactions/', methods=['GET', 'POST', 'PUT', 'DELETE'])
def transactions():
    '''Transaction.transaction_pool 정보를 읽어서 리턴'''
    block_chain = get_blockchain()
    if request.method=='GET':
        '''transaction 정보 요청'''
        resp = {
            'transactions': block_chain.get('transaction_pool'),
            'length': len(block_chain.get('transaction_pool')),
        }
        return jsonify(resp), 200

    if request.method=='POST':
        '''transaction 추가'''
        request_json = request.json
        validate_success = utils.validate_transaction_params(request_json)
        if not validate_success:
            return jsonify({'message': 'missing required params'}), 400

        transfer = Transfer(
            send_public_key=request_json.get('send_public_key'),
            send_blockchain_addr=request_json.get('send_blockchain_addr'),
            recv_blockchain_addr=request_json.get('recv_blockchain_addr'),
            amount=request_json.get('amount'),
            signature=request_json.get('signature'),
        )
        is_transacted = transfer.create_transaction()

        if not is_transacted:
            return jsonify({'status': 'fail'}), 400
        return jsonify({'status': 'success'}), 201


    if request.method=='PUT':
        '''transaction 추가요청이 있을 경우 업데이트'''
        request_json = request.json
        validate_success = utils.validate_transaction_params(request_json)

        if not validate_success:
            return jsonify({'message': 'missing required params'}), 400

        transfer = Transfer(
            send_public_key=request_json.get('send_public_key'),
            send_blockchain_addr=request_json.get('send_blockchain_addr'),
            recv_blockchain_addr=request_json.get('recv_blockchain_addr'),
            amount=request_json.get('amount'),
            signature=request_json.get('signature'),
        )
        is_updated = transfer.add_transaction()

        if not is_updated:
            return jsonify({'status': 'fail'}), 400
        return jsonify({'status': 'success'}), 200

    # DB를 사용할 경우 transaction 정보를 삭제하지 않음
    # on-memory cache를 사용할 경우 필요
    # if request.method == 'DELETE':
    #     '''Transaction pool 초기화 요청이 있을 경우 비워버리기'''
    #     transactions = Transaction.query.all()
    #     for transaction in transactions:
    #         db.session.delete(transaction)
    #         db.session.commit()


@bp.route('/mining/', methods=['GET', 'POST'])
def mining():
    '''채굴 실행'''
    json_data = request.json
    recv_blockcain_addr = json_data.get('blockchain_addr')
    print(f'miner_blockchain_addr: {recv_blockcain_addr}')
    mine = Mine()

    # 채굴 성공했을때 보상받을 주소
    # 나중에 wallet server로부터 전달받도록 코딩
    # recv_blockcain_addr = '123'
    mining_success, reason = mine.mining(recv_blockcain_addr)
    if mining_success:
        return jsonify({'status': 'success'}), 200

    return jsonify({
            'status': 'fail',
            'reason': reason,}), 200


@bp.route('/mining/start/', methods=['GET'])
def mining_start():
    '''채굴 실행'''
    mine = Mine()
    mine.start_mining()
    return jsonify({'status': 'success'}), 200


@bp.route('/coin_amount/', methods=['POST'])
def coin_amount():
    blockchain_addr = request.json['blockchain_addr']
    print(f'blockchain_addr: {blockchain_addr}')
    if not blockchain_addr:
        return jsonify({
                'status': 'fail',
                'content': '지갑주소(blockchain address)가 없습니다.'
        })
    return jsonify({
        'status': 'success',
        'content': Wallet().calculate_total_amount(blockchain_addr),
    })

@bp.route('/resolve_conflicts/', methods=['PUT'])
def resolve_conflicts():
    '''가장 긴 블록체인을 찾아서 검증 -> 교체
        - 호출 시기: 개별 노드가 채굴에 성공했을 경우
        - 실행 순서: 채굴 성공 -> 블록 생성 -> 이웃 노드에게 resolve conflict 요청
    '''
    blockchain = BlockChain()
    resolve_result = blockchain.resove_conflicts()
    return jsonify({
        'status': 'success' if resolve_result else 'fail',
        'content': 'resolve_conflicts'
    }), 200

server/templates/base.html
<!DOCTYPE html>
{% autoescape false %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>채굴</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</head>
<body>
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8 shadow-lg p-1 my-5 bg-body-tertiary rounded">
            {% include 'nav_bar.html' %}
        </div>
        <div class="col-sm-2"></div>
    </div>
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-sm-2"></div>
    </div>
</body>
</html>
{% endautoescape %}

server/templates/index.html
{% extends 'base.html' %}

{% block content%}
    <script src="/static/js/seed_server.js"></script>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <script type="text/javascript">
        alert("{{messages[-1]}}");
    </script>
    {% endif %}
    {% endwith %}

    <div class="row">

    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            씨쥬 코인 채굴(mining) 서버에 오신것을 환영합니다.
        </div>
        <div class="col-sm-1"></div>
    </div>

    <div class="row my-3">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <a href="" class="btn btn-outline-primary"
                id="find-blockchain-nodes"
                data-seed="{{ seed_host }}/node_list"
                data-ip="{{ ip }}"
                data-port="{{ port }}">
                블록체인 노드 확인
            </a>
        </div>
        <div class="col-sm-1"></div>
    </div>

    <div>
        <div href="" class="btn btn-outline-primary"
            id="request-blockchain-nodes"
            data-seed="{{ seed_host }}/node_list"></div>
    </div>


    <div class="row my-3 mx-3" id="form-area">
        <div class="shadow p-3 mb-5 bg-white rounded">
            <form method="post" id="transfer-form">
                <!-- Form 오류 표시 -->
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field, errors in form.errors.items() %}
                    <strong>{{ form[field].label }}</strong>
                    <ul>
                        {% for error in errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endfor %}
                </div>
                {% endif %}

                {{ form.csrf_token }}

                <div class="my-5">
                    <label for="private_key" class="form-label">
                        본인의 비밀키(Private Key)
                    </label>
                    <input type="password" class="form-control"
                        id="private_key" name="private_key"
                        autoComplete="off"
                        value="{{ form.private_key.data or '' }}"
                        placeholder="본인의 비밀키(Private Key)를 입력해 주세요.">
                </div>
                <div class="my-5">
                    <label for="public_key" class="form-label">
                        본인의 공개키(Public Key)
                    </label>
                    <input type="password" class="form-control"
                        id="public_key" name="public_key"
                        autoComplete="off"
                        value="{{ form.public_key.data or '' }}"
                        placeholder="본인의 공개키(Public Key)를 입력해 주세요.">
                </div>
                <div class="my-5">
                    <label for="my_blockchain_addr" class="form-label">본인의 지갑 주소</label>
                    <input type="text" class="form-control"
                        id="my_blockchain_addr" name="my_blockchain_addr"
                        autoComplete="off"
                        value="{{ form.my_blockchain_addr.data or '' }}"
                        placeholder="본인의 지갑 주소를 입력해주세요.">
                </div>
                <button class="btn btn-outline-primary" id="submit-btn">채굴시작</button>
                <a href="{{ url_for('main.home') }}" class="btn btn-outline-primary">내용 초기화</a>
            </form>
        </div>
    </div>



{% endblock %}

server/templates/mining.html
{% extends 'base.html' %}

{% block content%}

    <script src="/static/js/mining.js"></script>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <script type="text/javascript">
        alert("{{ messages[-1]}} ");
    </script>
    {% endif %}
    {% endwith %}

    <p class="my-3">씨쥬 코인 마이닝을 시작합니다.</p>
    <p class="my-3">채굴을 시도하는 동안에는 반드시 컴퓨터가 켜져 있어야 합니다.</p>
    <div class="row my-3">
        <div class="col-sm">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="miner_wallet_addr">
                        전자지갑 주소
                    </span>
                </div>
                <input type="text" class="form-control" id="blockchain_addr_input"
                    value="{{ form.my_blockchain_addr.data or '' }}">
            </div>
        </div>
    </div>
    <div class="row my-3">
        <div class="col-sm">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon3">
                        <div class="btn btn-outline-primary" id="query_coin_status">
                            내 코인 조회
                        </div>
                    </span>
                </div>
                <input type="text" class="form-control" id="current_coin_amount"
                    readonly
                    value="">
            </div>
        </div>
    </div>    
    <div class="row my-3" id="after-transfer">
        <div class="col-sm">
            <a href="#" class="btn btn-outline-primary" id="start_mining">채굴 시작!</a>
            
        </div>
    </div>


{% endblock %}

server/templates/nav_bar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottomd-flex ">
  <div class="container-fluid nav-pills d-flex justify-content-center text-center ">

    <!-- 햄버거 메뉴 -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span>
        메뉴 열기<span class="navbar-toggler-icon"></span>
      </span>
    </button>

    <div
      class="collapse navbar-collapse nav justify-content-center"
      id="navbarSupportedContent">

      <a class="navbar-brand" href="{{ url_for('main.home') }}">Home</a>
      <ul class="nav nav-pills">

        

      </ul>
    </div>
  </div>
</nav>